config/routes.rb
Rails.application.routes.draw do
  devise_for :systems,
    path:        'system',
    path_names:  {sign_in: 'login', sign_out: 'logout'},
    only:        [:sessions],
    controllers: { sessions: 'system/sessions' }

  devise_for :companies,
    path:        'bid',
    path_names:  {sign_in: 'login', sign_out: 'logout'},
    only:        [:sessions],
    controllers: { sessions: 'bid/sessions' }

  devise_for :users,
    path: :users,
    path_names: {sign_in: 'login', sign_out: 'logout'},
    controllers: { registrations: 'users/registrations', confirmations: 'users/confirmations', sessions: 'users/sessions' }
  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end

  root to: "main#index"
  get "mltest" => "main#get_ml_genre"
  get "qrcode" => "main#qrcode"
  get "search" => "main#search"


  # get  "search"                      => "products#index", as: :search
  get  "xl_genre/:xl_genre_id"       => "products#index", as: :xl_genre
  get  "large_genre/:large_genre_id" => "products#index", as: :large_genre
  get  "genre/:genre_id"             => "products#index", as: :genre
  get  "special/:special_key"        => "products#index", as: :special

  # get  "detail/:id"   => "products#show"
  get "detail/:id" => redirect("/products/%{id}")

  resources :products, only: [:index, :show] do
    collection do
      get  :list_no
      get  :image_vector_search_by_file
      post :image_vector_search_by_file
      get  :image
      get  :search_by_list_no
    end

    member do
      get :image_vector_search
      get :images
      get :youtube
    end
  end

  # get  "images/:id"   => "products#images"
  # get  "youtube/:id"  => "products#youtube"
  # get  "bid_list"     => "products#bid_list"
  # get  "search_by_list_no" => "products#search_by_list_no"

  get "images/:id"  => redirect("/products/%{id}/images")
  get "youtube/:id" => redirect("/products/%{id}/youtube")
  get "bid_list"    => redirect("/products/list_no")
  get "search_by_list_no" => "products#search_by_list_no"

  get  "ml_get_genre" => "products#ml_get_genre"

  get  "qr"         => "products#qr"
  # get  "contact/:id"     => "products#contact"
  # post "contact/:id"     => "products#contact_do"
  # get  "contact_tel/:id" => "products#contact_tel"

  # get  "search_by_ml"      => "products#search_by_ml"

  # resources :wishlist, only: [:index, :create, :destroy]

  resources :contacts, only: [:new, :create] do
    collection do
      get :fin
    end
  end

  resources :detail_logs,  only: [:create]
  resources :toppage_logs, only: [:create]
  resources :search_logs,  only: [:create]

  # resources :helps, only: [:show]
  resources :helps, only: [] do
    collection do
      get :beginner
      get :faq
    end
  end

  get "search" => "main#search"


  ### マイページ ###
  namespace :mypage do
    root to: "main#index"

    get   'edit_password' => 'main#edit_password'
    patch 'edit_password' => 'main#update_password'
    get   'edit_user'     => 'main#edit_user'
    patch 'edit_user'     => 'main#update_user'

    resources :products,  only: [:index]
    resources :favorites, only: [:index, :create, :destroy] do
      collection do
        post  "toggle"
        patch "request_list"
      end
    end
    resources :contacts,  only: [:new, :create]
  end

  namespace :system do
    root to: "main#index"

    get   'edit_password' => 'main#edit_password'
    patch 'edit_password' => 'main#update_password'

    resources :opens do
      member do
        get "detail/:product_id" => :result_detail
      end

      member do
        get   :products
        get   :detail_logs
      end
    end
    resources :companies, except: [:show, :delete]
    resources :areas,     except: [:show]
    resources :infos,     only: [:index, :edit, :update]
    resources :displays,  only: [:index, :edit, :update]

    resources :products, except: [:show] do
      collection do
        get   :images
        get   :csv
        post  "csv" => :csv_upload
        patch "csv" => :csv_import
      end

      member do
        post   :image_upload
        delete ":product_image_id" => :image_destroy
        patch  :images_order
      end
    end

    resources :bids, except: [:show] do
      collection do
        # get :results
        get :rakusatsu_sum
        get :shuppin_sum
        get :total
        get :total_list
      end
    end

    resources :list, only: [:index, :new, :edit, :update] do
      collection do
        get :hangtag
        get :ef
        get :carry_out
        get :qr

        get    "carryout"     => :carryout_new
        get    "carryout/:id" => :carryout_edit
        patch  "carryout/:id" => :carryout_update
        delete "carryout/:id" => :carryout_destroy

        get :ads
      end
    end

    resources :bt, only: [:index, :new, :edit, :update] do
      collection do
        get    "carryout"     => :carryout_new
        get    "carryout/:id" => :carryout_edit
        patch  "carryout/:id" => :carryout_update
        delete "carryout/:id" => :carryout_destroy
      end
    end

    resources :users,        only: [:index, :show, :destroy]
    resources :contacts,     only: [:index]
    resources :favorites,    only: [:index]
    resources :detail_logs,  only: [:index]
    resources :toppage_logs, only: [:index]
    resources :search_logs,  only: [:index]

    resources :scheduling, only: [:index] do
      collection do
        post 'vectors_process'
        get  'recommend_products_mail'
        get  'tracking/:r/:dummy' => :tracking
      end
    end

    resources :total,  only: [:index] do
      collection do
        # get 'goal'
        get 'index2'
        get 'opens'
        get 'formula'
      end
    end

    unless Rails.env.production?
      resources :playground, only: [:show] do
        collection do
          get 'search_01'
          get 'search_02'
          post 'search_02'
          get 'image'

          get 'kmeans_01'


          get 'vector_maker'
          get 'vector_maker_solo'

          get "mock_list_01"
          get "mock_list_02"

          get 'vector_search_json'
        end
      end
    end

    resources :mailchimp_html, only: [:index]
    resources :mailchimp_user_html, only: [:index]
  end

  namespace :bid do
    root to: "main#index"

    get    'edit_password' => 'main#edit_password'
    patch  'edit_password' => 'main#update_password'

    get   'rule' => 'main#rule'
    patch 'rule' => 'main#rule_update'

    resources :products, except: [:show] do
      collection do
        get   :images
        get   :csv
        post  "csv" => :csv_upload
        patch "csv" => :csv_import
        get   :sim
      end

      member do
        post   :image_upload
        delete ":product_image_id" => :image_destroy
        patch  :images_order
      end
    end

    resources :bids, except: [:show] do
      collection do
        # get :results
        get :rakusatsu_sum
        get :shuppin_sum
        get :total
        get :motobiki
      end
    end

    resources :opens, only: [:index, :show]

    # resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
    #   collection do
    #     get   :csv
    #     post  "csv" => :csv_upload
    #     patch "csv" => :csv_import
    #   end
    # end
    #
    # resources :requests, only: [:index, :show, :update]
  end

  get '*path' => 'application#routing_error'
end

app/controllers/system/application_controller.rb
class System::ApplicationController < ApplicationController
  before_action :authenticate_system!

  layout 'layouts/application'

  private

  def get_companies_selector
    @companies_selector = Company.order(:no).pluck("no || ' : ' || name", :id)
    session[:system_company_id] = params[:company_id] if params[:company_id].present?

    @company = Company.find_by(id: session[:system_company_id]) if session[:system_company_id].present?
  end

  def check_open
    redirect_to "/system/", notice: "現在、開催されている入札会はありません" unless @open_now
  end

  def check_entry_start
    redirect_to "/system/", notice: "現在、出品期間ではありません" unless @open_now.entry_start?
  end

  def check_bid_start
    redirect_to "/system/", notice: "現在、入札期間ではありません" unless @open_now.bid_start?
  end

  def check_result_list
    redirect_to "/system/", notice: "落札結果表示まで、しばらくお待ち下さい" unless @open_now.result_list?
  end

  def check_result_sum
    redirect_to "/system/", notice: "計算表表示まで、しばらくお待ち下さい" unless @open_now.result_sum?
  end
end

app/controllers/system/areas_controller.rb
class System::AreasController < System::ApplicationController
  before_action :get_area, only: [:edit, :update, :destroy]

  def index
    @areas = Area.all.order(:order_no)
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    if @area.save
      redirect_to "/system/areas/", notice: "#{@area.name}を登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @area.update(area_params)
      redirect_to "/system/areas/", notice: "#{@area.name}を変更しました"
    else
      render :edit
    end
  end

  def destroy
    @area.soft_destroy!
    redirect_to "/system/areas/", notice: "#{@area.name}を削除しました"
  end

  private

  def get_area
    @area = Area.find(params[:id])
  end

  def area_params
    params.require(:area).permit(:name, :image, :order_no, :remove_image)
  end
end

app/controllers/system/bids_controller.rb
class System::BidsController < System::ApplicationController
  before_action :check_open
  before_action :check_bid_start,   only: [:index, :new, :create, :destroy, :edit, :update, :destroy]
  before_action :check_result_list, only: [:results]
  before_action :check_result_sum,  only: [:rakusatsu_sum, :shuppin_sum, :total, :total_list]
  before_action :calc_result,       only: [:rakusatsu_sum, :shuppin_sum, :total, :total_list]

  before_action :get_companies_selector, except: [:results]
  before_action :bids, except: [:results]

  before_action :bid_init, only: [:new, :create]
  before_action :get_bid, only: [:edit, :update, :destroy]

  include Exports

  def index
    respond_to do |format|
      format.html
      format.pdf { export_pdf "#{@open_now.name}_bids.pdf", "/bid/bids/index.pdf" }
      format.csv { export_csv "#{@open_now.name}_bids.csv", "/bid/bids/index.csv" }
    end
  end

  def new
  end

  def create
    @bid.assign_attributes(bid_params)
    if params[:overcheck].to_i != @bid.amount && @over = @bid.check_5time
      render :new
    elsif @bid.present? && @bid.save
      redirect_to "/system/bids/new", notice: "#{@bid.product.name}に入札しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @bid.assign_attributes(bid_params)
    if params[:overcheck].to_i != @bid.amount && @over = @bid.check_5time
      render :edit
    elsif @bid.save
      redirect_to "/system/bids/", notice: "#{@bid.product.list_no} : #{@bid.product.name}の入札を訂正しました"
    else
      render :edit
    end
  end

  def rakusatsu_sum
    if @company
      @search   = @open_now.bids.where(company: @company).includes(:product, :genre, :success_bid).search(params[:q])
      @bids     = @search.result.order(:created_at)

      respond_to do |format|
        format.html
        format.pdf { export_pdf "rakusatsu.pdf", "/bid/bids/rakusatsu_sum.pdf" }
        format.csv { export_csv "rakusatsu.csv", "/bid/bids/rakusatsu_sum.csv" }
      end
    end
  end

  def shuppin_sum
    if @company
      @search   = @open_now.products.listed.where(company: @company).includes(:genre, :success_bid, :success_company).search(params[:q])
      @products = @search.result.order(:list_no)

      respond_to do |format|
        format.html
        format.csv { export_csv "shuppin.csv", "/bid/bids/shuppin_sum.csv" }
      end

    end
  end

  def total
    if @company
      @products         = @open_now.products.listed.where(company: @company).includes(:success_bid)
      @success_products = @open_now.bids.where(company: @company).includes(:product, :success_bid).success_products
    end
  end

  def destroy
    @bid.soft_destroy!
    redirect_to "/system/bids/", notice: "#{@bid.product.name}の入札を取り消しました"
  end

  def total_list
    all_products = @open_now.products.listed.includes(:success_bid, :success_company, :company)
    all_bids     = @open_now.bids.includes(:product, :success_bid, :product_company, :company)
    @companies = Company.order(:no)

    @company_products = @companies.map do |c|
      [
        c.id,
        {
          products:         all_products.where(company: c).order(:list_no),
          success_products: all_bids.where(company: c).success_products
        }
      ]
    end.to_h

    respond_to do |format|
      format.html
      # format.pdf { export_pdf "#{@open_now.name}_精算表.pdf" }
      format.pdf
      format.csv { export_csv "total.csv" }
    end
  end

  private

  def select_company_bids
    @companies = Company.order(:no).pluck("no || ' : ' || name", :id)

    session[:system_company_id] = params[:company_id] if params[:company_id].present?

    if session[:system_company_id].present? && @company = Company.find_by(id: session[:system_company_id])
      @search = @open_now.bids.where(company_id: session[:system_company_id]).search(params[:q])
      @bids   = @search.result
    else
      session[:system_company_id] = nil
      flash[:notice] = "会社を選択してください"
    end
  end

  def bids
    @search = @open_now.bids.where(company: @company).includes(:product, :genre).search(params[:q])
    @bids   = @search.result.order(created_at: :desc)
  end

  def bid_init
    @product = params[:list_no].present? ? @open_now.products.find_by(list_no: params[:list_no]) : nil
    @bid     = @product.bids.new(company: @company) if @product
  end

  def get_bid
    @bid = @bids.find(params[:id])
  end

  def calc_result
    @open_now.result_sum unless @open_now.result
  end

  def bid_params
    params.require(:bid).permit(:product_id, :amount, :comment)
  end
end

app/controllers/system/bt_controller.rb
class System::BtController < System::ApplicationController
  before_action :get_companies_selector, only: [:hangtag, :ef, :carryout_new, :carryout_edit]
  before_action :check_open
  before_action :check_entry_date
  before_action :get_product,   only: [:edit, :update, :carryout_edit, :carryout_update, :carryout_destroy]
  before_action :get_selectors, only: [:new, :edit]

  layout 'system/bt'

  def index

  end

  ### 入庫処理 ###
  def new
    # 入力キー変換
    key = params[:key].to_s.normalize_charwidth.gsub(/[―ー−‐]/, '-').strip

    if key =~ /^([0-9]+)\-([0-9]+)\-([0-9]+)$/
      product = Product.includes(:company).find_by(open_id: $1, companies: {no: $2}, app_no: $3)
      if product.blank?
        flash.now[:alert] = "商品情報なし\n#{key}"
      else
        redirect_to "/system/bt/#{product.id}/edit"
      end
    else
      flash.now[:alert] = "フォーマットエラー\n#{key}" unless key.blank?
    end
  end

  def edit
    # @product.list_no ||= @open_now.products.max_list_no + 1 # デフォルト値

    @product.area_id ||= session[:system_area_id]

    @products          = @open_now.products.includes(:company).where(company_id: @product.company_id).order(:app_no)
    @products_selector = @products.order(:app_no).pluck("app_no || ' : ' || products.name || ' ' || coalesce(maker, '-') || ' ' || coalesce(model, '-')", :id) if @products.present?
  end

  def update
    # 店頭出品の初期化
    if tento_products = @open_now.products.where(display: "店頭出品", list_no: nil).order(:company_id, :app_no)
      max_list_no = @open_now.products.max_list_no
      tento_products.each do |p|
        p.list_no = (max_list_no += 1)
        p.save
      end
    end

    lp = list_no_params
    session[:system_area_id] = lp[:area_id]

    lp[:list_no] = @open_now.products.max_list_no + 1 if lp[:list_no].blank? # デフォルト値

    if @product.update(lp)
      redirect_to "/system/bt/new", notice: "入庫確認 No. #{@product.list_no}\n#{@product.name}"
    else
      render :edit
    end
  end

  ### 出庫処理 ###
  def carryout_new
    # 入力キー変換
    key = params[:key].to_s.normalize_charwidth.gsub(/[―ー−‐]/, '-').strip

    if key =~ /id\=([0-9]+)/
      product = Product.includes(:company).find_by(id: $1)

      if product.blank?
        flash.now[:alert] = "商品情報なし\n#{key}"
      else
        redirect_to "/system/bt/carryout/#{product.id}/"
      end
    else
      flash.now[:alert] = "フォーマットエラー\n#{key}" unless key.blank?
    end
  end

  def carryout_edit
    @products = @open_now.products.includes(:company).where(company_id: @product.company_id).order(:app_no)
  end

  def carryout_update
    @product.update(carryout_at: Time.now)
    redirect_to "/system/bt/carryout", notice: "No. #{@product.list_no} : #{@product.name}の出庫確認しました"
  end

  def carryout_destroy
    @product.update(carryout_at: nil)
    redirect_to "/system/bt/carryout", notice: "No. #{@product.list_no} : #{@product.name}の出庫をキャンセルしました"
  end

  private

  def check_open
    redirect_to "/system/", alert: "現在、開催されている入札会はありません" unless @open_now
  end

  def check_entry_date
    redirect_to "/system/", alert: "現在、出品期間ではありません" unless @open_now
  end

  def get_product
    @product = @open_now.products.find(params[:id])
  end

  def get_companies_selector
    @compaies_selector = Company.order(:no).pluck("no || ' : ' || name", :id)
  end

  def get_selectors
    get_companies_selector
    @areas_selector = Area.order(:order_no).pluck(:name, :id)
  end

  def list_no_params
    params.require(:product).permit(:list_no, :area_id)
  end
end

app/controllers/system/contacts_controller.rb
class System::ContactsController < System::ApplicationController
  def index
    @contacts  = Contact.all.order(id: :desc)

    @pcontacts = @contacts.page(params[:page])
  end
end

app/views/system/companies/_form.html.slim
table.table.table-hover.table-condensed.form-table
  tr
    th ID
    td = f.object.id || "新規登録"
  tr
    th = f.label :name, class: :required
    td = f.text_field :name, class: "form-control",  required: "required"

  tr
    th = f.label :no
    td = f.number_field :no, class: "form-control",  required: "required"

  tr
    th = f.label :registration_number
    td = f.text_field :registration_number, class: "form-control"

  tr
    th = f.label :charge
    td = f.text_field :charge, class: "form-control"

  tr
    th = f.label :representative
    td = f.text_field :representative, class: "form-control"

  tr
    th = f.label :position
    td = f.text_field :position, class: "form-control"

  tr
    th = f.label :zip
    td = f.text_field :zip, class: "form-control"

  tr
    th = f.label :address
    td = f.text_field :address, class: "form-control"

  tr
    th = f.label :tel
    td = f.text_field :tel, class: "form-control"

  tr
    th = f.label :fax
    td = f.text_field :fax, class: "form-control"

  tr
    th = f.label :mail
    td = f.text_field :mail, class: "form-control", autocomplete: "new-password"

  tr
    th = f.label :memo
    td = f.text_area :memo, class: "form-control"

  tr
    th = f.label :entry, class: :required
    td
      label.radio-inline
        = f.radio_button :entry, true
        | 可
      label.radio-inline
        = f.radio_button :entry, false
        | 不可

  tr
    th = f.label :transfer, class: :required
    td
      label.radio-inline
        = f.radio_button :transfer, true
        | 振込
      label.radio-inline
        = f.radio_button :transfer, false
        | 小切手
    tr
      th = f.label :account, class: :required
      td = f.text_field :account, class: "form-control", required: "required"

  - if f.object.id.blank?
    tr
      th = f.label :password, class: :required
      td = f.password_field :password, class: "form-control", autocomplete: "new-password", placeholder: "パスワードは半角英数8文字以上", required: "required"
  - else
    tr
      th = f.label :password, "パスワード変更"
      td = f.password_field :password, class: "form-control", autocomplete: "new-password", placeholder: "パスワードは半角英数8文字以上"
    / tr
    /   th = f.label :password_confirmation, "パスワード変更(確認)"
    /   td = f.password_field :password_confirmation, class: "form-control", placeholder: "確認用"

= f.button :button, data: { confirm: "保存してよろしいでしょうか", "disable-with" => "保存中..."}, class: "btn btn-default btn-square btn-submit center-block" do
  span.glyphicon.glyphicon-save
  span.btn-content 保存

app/views/system/companies/edit.html.slim
- set_meta_tags title: "会社変更"
- breadcrumb  :system_companies_edit, @company

.col-md-offset-3.col-md-6
  - if @company.errors.full_messages.present?
    .alert.alert-danger
      ul
        - @company.errors.full_messages.each do |msg|
          li = msg
  = form_for @company, url: system_company_path, method: :patch do |f|
    = render "form", f: f

app/views/system/companies/index.html.slim
- set_meta_tags title: "会員一覧"
- breadcrumb :system_companies

ul.nav.nav-pills
  li = link_to "/system/companies/new", class: "btn btn-default btn-square" do
    span.glyphicon.glyphicon-plus
    span.btn-content 新規会社登録
  li = link_to({ format: :csv }, { class: "btn btn-default btn-square" }) do
    span.glyphicon.glyphicon-download-alt
    span.btn-content CSV出力

- if @companies.blank?
  div 会社がありませんでした
- else
  .row.container-fluid.list-menu
    / .page-area
    /   | #{number_with_delimiter(@pdatas.total_count)}件 :
    /   | #{number_with_delimiter(@pdatas.offset_value + 1)}件 〜
    /   | #{number_with_delimiter(@pdatas.offset_value + @pdatas.length)}件を表示中
    /
    /   = paginate @pdatas

    .scroll_div
      table.table.table-striped.table-hover.table-condensed.table-bordered.table-responsive _fixedhead='rows:1'
        tr
          / th.id ID
          th.id No.
          th 会社名
          th 出品
          th 登録番号
          th 住所
          th TEL
          th FAX
          th メールアドレス
          th 振込
          th アカウント
          th 作成日時
        - @companies.each do |c|
          tr
            / td.id = c.id
            td.id = c.no
            td = link_to c.name, "/system/companies/#{c.id}/edit"
            td = c.entry ? "◯" : "☓"
            td = c.registration_number
            td = c.address
            td = c.tel
            td = c.fax
            td = mail_to c.mail
            td = c.transfer? ? "◯" : ""
            td = c.account
            td = c.created_at
            / td
            /   - message = "#{c.no} : #{c.name}\n\nこの会社を削除しますか？"
            /   = link_to "/system/companies/#{c.id}/", method: :delete, data: { confirm: message, "disable-with" => "削除中..."}, class: "btn btn-danger" do
            /     span.glyphicon.glyphicon-remove
            /     =< "削除"

app/views/system/companies/new.html.slim
- set_meta_tags title: "会社新規登録"
- breadcrumb  :system_companies_new

.col-md-offset-3.col-md-6
  - if @company.errors.full_messages.present?
    .alert.alert-danger
      ul
        - @company.errors.full_messages.each do |msg|
          li = msg
  = form_for @company, url: "/system/companies", method: :post do |f|
    = render "form", f: f