config/routes.rb
Rails.application.routes.draw do
  devise_for :systems,
    path:        'system',
    path_names:  {sign_in: 'login', sign_out: 'logout'},
    only:        [:sessions],
    controllers: { sessions: 'system/sessions' }

  devise_for :companies,
    path:        'bid',
    path_names:  {sign_in: 'login', sign_out: 'logout'},
    only:        [:sessions],
    controllers: { sessions: 'bid/sessions' }

  devise_for :users,
    path: :users,
    path_names: {sign_in: 'login', sign_out: 'logout'},
    controllers: { registrations: 'users/registrations', confirmations: 'users/confirmations', sessions: 'users/sessions' }
  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end

  root to: "main#index"
  get "mltest" => "main#get_ml_genre"
  get "qrcode" => "main#qrcode"
  get "search" => "main#search"


  # get  "search"                      => "products#index", as: :search
  get  "xl_genre/:xl_genre_id"       => "products#index", as: :xl_genre
  get  "large_genre/:large_genre_id" => "products#index", as: :large_genre
  get  "genre/:genre_id"             => "products#index", as: :genre
  get  "special/:special_key"        => "products#index", as: :special

  # get  "detail/:id"   => "products#show"
  get "detail/:id" => redirect("/products/%{id}")

  resources :products, only: [:index, :show] do
    collection do
      get  :list_no
      get  :image_vector_search_by_file
      post :image_vector_search_by_file
      get  :image
      get  :search_by_list_no
    end

    member do
      get :image_vector_search
      get :images
      get :youtube
    end
  end

  # get  "images/:id"   => "products#images"
  # get  "youtube/:id"  => "products#youtube"
  # get  "bid_list"     => "products#bid_list"
  # get  "search_by_list_no" => "products#search_by_list_no"

  get "images/:id"  => redirect("/products/%{id}/images")
  get "youtube/:id" => redirect("/products/%{id}/youtube")
  get "bid_list"    => redirect("/products/list_no")
  get "search_by_list_no" => "products#search_by_list_no"

  get  "ml_get_genre" => "products#ml_get_genre"

  get  "qr"         => "products#qr"
  # get  "contact/:id"     => "products#contact"
  # post "contact/:id"     => "products#contact_do"
  # get  "contact_tel/:id" => "products#contact_tel"

  # get  "search_by_ml"      => "products#search_by_ml"

  # resources :wishlist, only: [:index, :create, :destroy]

  resources :contacts, only: [:new, :create] do
    collection do
      get :fin
    end
  end

  resources :detail_logs,  only: [:create]
  resources :toppage_logs, only: [:create]
  resources :search_logs,  only: [:create]

  # resources :helps, only: [:show]
  resources :helps, only: [] do
    collection do
      get :beginner
      get :faq
    end
  end

  get "search" => "main#search"


  ### マイページ ###
  namespace :mypage do
    root to: "main#index"

    get   'edit_password' => 'main#edit_password'
    patch 'edit_password' => 'main#update_password'
    get   'edit_user'     => 'main#edit_user'
    patch 'edit_user'     => 'main#update_user'

    resources :products,  only: [:index]
    resources :favorites, only: [:index, :create, :destroy] do
      collection do
        post  "toggle"
        patch "request_list"
      end
    end
    resources :contacts,  only: [:new, :create]
  end

  namespace :system do
    root to: "main#index"

    get   'edit_password' => 'main#edit_password'
    patch 'edit_password' => 'main#update_password'

    resources :opens do
      member do
        get "detail/:product_id" => :result_detail
      end

      member do
        get   :products
        get   :detail_logs
      end
    end
    resources :companies, except: [:show, :delete]
    resources :areas,     except: [:show]
    resources :infos,     only: [:index, :edit, :update]
    resources :displays,  only: [:index, :edit, :update]

    resources :products, except: [:show] do
      collection do
        get   :images
        get   :csv
        post  "csv" => :csv_upload
        patch "csv" => :csv_import
      end

      member do
        post   :image_upload
        delete ":product_image_id" => :image_destroy
        patch  :images_order
      end
    end

    resources :bids, except: [:show] do
      collection do
        # get :results
        get :rakusatsu_sum
        get :shuppin_sum
        get :total
        get :total_list
      end
    end

    resources :list, only: [:index, :new, :edit, :update] do
      collection do
        get :hangtag
        get :ef
        get :carry_out
        get :qr

        get    "carryout"     => :carryout_new
        get    "carryout/:id" => :carryout_edit
        patch  "carryout/:id" => :carryout_update
        delete "carryout/:id" => :carryout_destroy

        get :ads
      end
    end

    resources :bt, only: [:index, :new, :edit, :update] do
      collection do
        get    "carryout"     => :carryout_new
        get    "carryout/:id" => :carryout_edit
        patch  "carryout/:id" => :carryout_update
        delete "carryout/:id" => :carryout_destroy
      end
    end

    resources :users,        only: [:index, :show, :destroy]
    resources :contacts,     only: [:index]
    resources :favorites,    only: [:index]
    resources :detail_logs,  only: [:index]
    resources :toppage_logs, only: [:index]
    resources :search_logs,  only: [:index]

    resources :scheduling, only: [:index] do
      collection do
        post 'vectors_process'
        get  'recommend_products_mail'
        get  'tracking/:r/:dummy' => :tracking
      end
    end

    resources :total,  only: [:index] do
      collection do
        # get 'goal'
        get 'index2'
        get 'opens'
        get 'formula'
      end
    end

    unless Rails.env.production?
      resources :playground, only: [:show] do
        collection do
          get 'search_01'
          get 'search_02'
          post 'search_02'
          get 'image'

          get 'kmeans_01'


          get 'vector_maker'
          get 'vector_maker_solo'

          get "mock_list_01"
          get "mock_list_02"

          get 'vector_search_json'
        end
      end
    end

    resources :mailchimp_html, only: [:index]
    resources :mailchimp_user_html, only: [:index]
  end

  namespace :bid do
    root to: "main#index"

    get    'edit_password' => 'main#edit_password'
    patch  'edit_password' => 'main#update_password'

    get   'rule' => 'main#rule'
    patch 'rule' => 'main#rule_update'

    resources :products, except: [:show] do
      collection do
        get   :images
        get   :csv
        post  "csv" => :csv_upload
        patch "csv" => :csv_import
        get   :sim
      end

      member do
        post   :image_upload
        delete ":product_image_id" => :image_destroy
        patch  :images_order
      end
    end

    resources :bids, except: [:show] do
      collection do
        # get :results
        get :rakusatsu_sum
        get :shuppin_sum
        get :total
        get :motobiki
      end
    end

    resources :opens, only: [:index, :show]

    # resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
    #   collection do
    #     get   :csv
    #     post  "csv" => :csv_upload
    #     patch "csv" => :csv_import
    #   end
    # end
    #
    # resources :requests, only: [:index, :show, :update]
  end

  get '*path' => 'application#routing_error'
end

app/controllers/bid/application_controller.rb
class Bid::ApplicationController < ApplicationController
  layout 'layouts/application'

  before_action :check_rule
  before_action :authenticate_company!
  before_action :check_default_password

  def check_rule
    redirect_to "/bid/rule" if session[:bid_rule].blank? || session[:bid_rule] < (Time.now - 12.hours)
  end

  def check_default_password
    if current_company.valid_password? "ikomamember"
      redirect_to "/bid/edit_password", notice: "初期パスワード「ikomamember」は、必ず変更する必要があります。\nパスワード変更をよろしくお願いします。"
    end
  end

  private

  def check_open
    redirect_to "/bid/", notice: "現在、開催されている入札会はありません" unless @open_now
  end

  def check_entry
    redirect_to "/bid/", notice: "現在、出品期間ではありません" unless @open_now.entry? && current_company.entry
  end

  def check_entry_start
    redirect_to "/bid/", notice: "現在、出品期間ではありません" unless @open_now.entry_start? && current_company.entry
  end

  def check_bid
    redirect_to "/bid/", notice: "現在、入札期間ではありません" unless @open_now.bid?
  end

  def check_result_list
    redirect_to "/bid/", notice: "落札結果表示まで、しばらくお待ち下さい" unless @open_now.result_list?
  end

  def check_result_sum
    redirect_to "/bid/", notice: "計算表表示まで、しばらくお待ち下さい" unless @open_now.result_sum?
  end

  def check_status(status)

  end

end

app/controllers/bid/bids_controller.rb
class Bid::BidsController < Bid::ApplicationController
  before_action :check_open
  before_action :check_bid,         only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :check_result_sum,  only: [:rakusatsu_sum, :shuppin_sum, :total, :motobiki]
  before_action :calc_result,       only: [:rakusatsu_sum, :shuppin_sum, :total, :motobiki]

  before_action :bids
  before_action :products, only: [:shuppin_sum, :total]

  before_action :bid_init, only: [:new, :create]
  before_action :get_bid, only: [:edit, :update, :destroy]

  include Exports

  protect_from_forgery

  def index
    respond_to do |format|
      format.html
      format.pdf { export_pdf "bids.pdf" }
      format.csv { export_csv "bids.csv" }
    end
  end

  def new
  end

  def create
    @bid.assign_attributes(bid_params)
    if params[:overcheck].to_i != @bid.amount && @over = @bid.check_5time
      render :new
    elsif @bid.present? && @bid.save
      redirect_to "/bid/bids/new", notice: "#{@bid.product.list_no} : #{@bid.product.name}に入札しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @bid.assign_attributes(bid_params)
    if params[:overcheck].to_i != @bid.amount && @over = @bid.check_5time
      render :edit
    elsif @bid.save
      redirect_to "/bid/bids/", notice: "#{@bid.product.list_no} : #{@bid.product.name}の入札を訂正しました"
    else
      render :edit
    end
  end

  def rakusatsu_sum
    @products = @products.order(:list_no)
    @bids     = @bids.order("products.list_no")
    @company  = current_company

    respond_to do |format|
      format.html
      format.pdf {
        if params[:hikitori]
          export_pdf "#{@open_now.name}_引取指図書.pdf", "/bid/bids/hikitori"
        else
          export_pdf "#{@open_now.name}_落札確認.pdf"
        end
      }
      format.csv { export_csv "rakusatsu.csv" }
    end
  end

  def shuppin_sum
    @products = @products.order(:app_no)
    @company  = current_company

    respond_to do |format|
      format.html
      format.csv { export_csv "shuppin.csv" }
    end
  end

  def total
    @products         = @products
    @success_products = @bids.success_products
  end

  def motobiki
    @search   = @open_now.products.listed.includes(:success_bid, :success_company, :area, :company).order(:list_no).search(params[:q])
    relation  = @search.result

    # @products = relation.where(company: current_company, display: "一般出品", success_bid_id: nil).or(relation.where(success_bid_id: Bid.where(company_id: current_company.id)))
    @products = relation.where(company: current_company, display: ["一般出品", "常設コマ", "単品預り"], success_bid_id: nil).or(relation.where(success_bid_id: Bid.where(company_id: current_company.id)))

    @company  = current_company

    respond_to do |format|
      format.html
      format.csv { export_csv "motobiki.csv" }
      format.pdf { export_pdf "motobiki.pdf" }
    end
  end

  def destroy
    @bid.soft_destroy!
    redirect_to "/bid/bids/", notice: "#{@bid.product.name}の入札を取り消しました"
  end

  private

  def bids
    @search = @open_now.bids.where(company: current_company).includes(:product, :genre, :success_bid, :product_company).search(params[:q])
    @bids   = @search.result.order(created_at: :desc)
  end

  def products
    @search   = @open_now.products.listed.where(company_id: current_company.id).includes(:success_bid, :success_company, :company, :genre, :large_genre, :xl_genre).search(params[:q])
    @products = @search.result
  end

  def bid_init
    @product = params[:list_no].present? ? @open_now.products.find_by(list_no: params[:list_no]) : nil
    @bid     = @product.bids.new(company: current_company) if @product
  end

  def get_bid
    @bid = @bids.find(params[:id])
  end

  def calc_result
    @open_now.result_sum unless @open_now.result
  end

  def bid_params
    params.require(:bid).permit(:product_id, :amount, :comment)
  end
end

app/controllers/bid/main_controller.rb
class Bid::MainController < Bid::ApplicationController
  skip_before_action :check_rule, only: [:rule, :rule_update]
  skip_before_action :authenticate_company!, only: [:rule, :rule_update]
  skip_before_action :check_default_password, only: [:rule, :rule_update, :edit_password, :update_password]

  def index
  end

  def edit_password
    @company = current_company
  end

  def update_password
    @company = current_company
    if @company.update_with_password(password_params)
      redirect_to "/bid/login", notice: 'パスワードを変更しましたので、再度ログインしてください'
    else
      render :edit_password
    end
  end

  def rule
  end

  def rule_update
    session[:bid_rule] = Time.now
    redirect_to "/bid/login"
  end

  private

  def password_params
    params.require(:company).permit(:password, :password_confirmation, :current_password)
  end
end

app/controllers/bid/opens_controller.rb
class Bid::OpensController < Bid::ApplicationController
  before_action :get_open, only: [:show]

  include Exports

  def index
    @opens = Open.order(bid_end_at: :desc)
  end

  def show
    redirect_to "/bid/opens/", alert: "#{@open.name}はまだ終了していません" if @open.bid_end_at > Time.now

    @open.result_sum unless @open.result

    @search    = @open.products.listed.with_keywords(params[:keywords])
      .includes(:success_bid, :success_company, :company, :genre, :product_images, :large_genre, :xl_genre, :area).search(params[:q])
    @products  = @search.result.order(:list_no).distinct
    @pproducts = @products.page(params[:page])

    @max_list_no = @open.products.listed.maximum(:list_no)

    @my_bids = current_company.bids.order(amount: :desc)

    respond_to do |format|
      format.html
      format.csv { export_csv "results.csv" }
    end
  end

  private

  def get_open
    @open = Open.find(params[:id])
  end
end

app/controllers/bid/requests_controller.rb
class Bid::RequestsController < Bid::ApplicationController
  before_action :check_open
  before_action :check_bid, only: [:index, :new, :update, :destroy]
  before_action :bid_init,  only: [:show, :update]


  def index
    @search   = @open_now.requests.where(company: current_company).includes(:product, :genre, :product_company).search(params[:q])

    @requests = @search.result.where(user_id: current_company.users).order(created_at: :desc)

    if params[:user_id].present?
      @user     = current_company.users.find(params[:user_id])
      @requests = @requests.where(user_id: params[:user_id])
    end
  end

  def new
  end

  def update
    if @bid.save
      @request.update(bided_at: Time.now)

      redirect_to "/bid/requests/", notice: "#{@request.user.company} #{@request.user.name}からの依頼に入札しました。\n\nNo. #{@product.list_no} : #{@product.name}"
    else
      render :new
    end
  end

  private

  def bid_init
    @request = current_company.requests.find(params[:id])
    @product = @open_now.products.find_by(list_no: @request.product[:list_no])
    @bid     = @product.bids.new(
      company: current_company,
      amount:  @request.amount,
      comment: "#{@request.user.company} #{@request.user.name}"
    ) if @product
  end

  def bid_params
    params.require(:bid).permit(:product_id, :amount, :comment)
  end

end

app/controllers/bid/result_controller.rb
class Bid::ResultController < Bid::ApplicationController
  def index
  end
end

app/controllers/bid/sessions_controller.rb
# frozen_string_literal: true

class Bid::SessionsController < Devise::SessionsController
  layout "/layouts/application"

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/mypage/products_controller.rb
class Mypage::ProductsController < Mypage::ApplicationController
  include Exports

  def index
    @products = @open_now.products.order(:list_no)

    respond_to do |format|
      format.csv { export_csv "#{@open_now.name}_products.csv" }
    end
  end
end

app/helpers/bid/bids_helper.rb
module Bid::BidsHelper
end

app/helpers/bid/products_helper.rb
module Bid::ProductsHelper
end

app/helpers/bid/requests_helper.rb
module Bid::RequestsHelper
end

app/helpers/bid/result_helper.rb
module Bid::ResultHelper
end

app/helpers/bid/users_helper.rb
module Bid::UsersHelper
end

app/views/bid/products/_csv.html.slim
coffee:
  $ ->
    $('.js-csv-upload').fileinput
      showPreview: false
      maxFileCount: 1
      browseClass: 'btn btn-info fileinput-browse-button'
      browseIcon: '<span class="glyphicon glyphicon-folder-open"></span>'
      browseLabel: ' ファイル選択'
      removeClass: 'btn btn-warning'
      removeIcon: '<span class="glyphicon glyphicon-remove"></span>'
      removeLabel: ' キャンセル'
      uploadClass: 'btn btn-success fileinput-upload-button'
      uploadIcon: '<i class="fa fa-upload"></i>'
      uploadLabel: ' アップロード'
      allowedFileExtensions: ['csv']
      msgValidationError: '''
        <span class="text-danger">
          <span class="glyphicon glyphicon-alert"></span>アップロードできるファイル形式はCSVです。
        </span>
      '''
      
.col-md-8.col-md-offset-2
   .form-group
     = label_tag :csv, "CSVファイル"
     = file_field_tag :file, class: "js-csv-upload", required: "required"
     .help-block
       li 機械名、最低入札金額は必須です
       li ジャンルは自動判別します
       li 一山は、空白だと「×」、何か入力されていると「◯」になります
       li 出品区分は、「一般出品」「常設コマ」「単品預り」「店頭出品」のいずれかを入力してください
   
   = button_tag(data: { "disable-with" => "アップロード中..."}, class: "btn btn-default btn-square btn-submit center-block") do
     span.glyphicon.glyphicon-upload
     =< "アップロード"

app/views/bid/products/_csv_upload.html.slim
.help-block
  . エラーがある商品は登録されません
          
= form_tag({action: :csv_import}, method: :patch, class: 'form-horizontal') do
  / = render "/bid/products/csv"
  .scroll_div
    table.table.table-striped.table-hover.table-condensed _fixedhead='rows:1;cols:1'
      tr
        th 申込No.
        th 商品名
        th エラー
        th メーカー
        th 型式
        th 一山
        th ジャンル
        th 最低入札金額
        th 年式
        th 仕様
        th 現状
        th 備考欄
        th 出品区分
        th youtube
        th 削除

      - @res.each do |p|
        tr
          td = p.app_no.presence || "新規"
          td = p.name
          td
            - p.errors.full_messages.each do |msg|
              li = msg
          td = p.maker
          td = p.model 
          td = p.hitoyama ? "◯" : "☓"
          td = p.genre.name
          td.num = number_to_currency(p.min_price)
          td = p.year
          td = simple_format(p.spec)
          td = simple_format(p.condition)
          td = p.comment
          td = p.display
          td = p.youtube
          td = "◯" if p.soft_destroyed_at.present?
          
        - if p.errors.blank?
          - [:app_no, :name, :maker, :model, :year, :spec, :condition, :comment, :min_price, :genre_id, :youtube, :display, :hitoyama, :soft_destroyed_at].each do |k|
            = hidden_field_tag "products[][#{k}]", p[k]
    
    = button_tag(data: { "disable-with" => "保存..."}, class: "btn btn-default btn-square btn-submit center-block") do
      span.glyphicon.glyphicon-save
      =< "一括登録"

app/views/bid/products/_form.html.slim
coffee:
  $ ->
    $('#check-youtube').click ->
      youtube = $('input.youtube').val()

      if !youtube
        alert "Youtubeの動画IDを入力してください"
        retur false

      if youtube.match(/watch\?v\=([a-zA-Z0-9-+]+)/)
        youtube = RegExp.$1
      else if youtube.match(/youtu\.be\/([a-zA-Z0-9-+]+)/)
        youtube = RegExp.$1

      window.open().location.href = "https://www.youtube.com/watch?v=" + youtube

.col-md-offset-2.col-md-8
  - if f.object.errors.full_messages.present?
    .alert.alert-danger
      ul
        - f.object.errors.full_messages.each do |msg|
          li = msg

  table.table.table-hover.table-condensed.form-table
    tr
      th ID
      td = f.object.id || "新規登録"
    tr
      th = f.label :app_no
      td
        - if request.path =~ /system/
          = f.text_field :app_no, class: "form-control"
        - else
          = f.object.app_no
    tr
      th = f.label :list_no
      td = f.object.list_no
    tr
      th = f.label :name, class: :required
      td
        - if @only_update
          = f.object.name
        - else
          = f.text_field :name, class: "form-control get_genre", required: "required"

    tr
      th = f.label :maker
      td
        - if @only_update
          = f.object.maker
        - else
          = f.text_field :maker, class: "form-control get_genre"

    tr
      th = f.label :model
      td
        - if @only_update
          = f.object.model
        - else
          = f.text_field :model, class: "form-control get_genre"

    tr
      th = f.label :hitoyama
      td.form-group
        = f.check_box :hitoyama, as: :boolean
        .help-block 一山や複数まとめて出品される場合はチェックしてください

    tr.form-inline
      th = f.label :min_price, class: :required
      td
        - if @only_update
          = number_to_currency(f.object.min_price)
        - else
          = (f.text_field :min_price, class: "form-control price", required: "required") + " 円"

    tr
      th = f.label :genre_id, "ジャンル", class: :required
      td
        - if @only_update
          span #{f.object.xl_genre.name} > #{f.object.large_genre.name} > #{f.object.genre.name}
        - else
          = f.select :genre_id, Genre.options, {include_blank: "-- ジャンルを選択 --"}, class: "form-control", required: "required"
          / = text_field_tag :genre, "", class: "form-control"
          = link_to "/bid/products/ml_get_genre.js", method: :get, remote: :true, class: "btn btn-success", onclick: "$('span.genre_loading').html('ジャンル検索中');$(this).attr('href', ('/ml_get_genre.js?' + $('input.get_genre').serialize()));" do
            span.glyphicon.glyphicon-search
            span.btn-content ジャンル検索
          span.genre_loading
    tr
      th = f.label :year
      td
        - if @only_update
          = f.object.year
        - else
          = f.text_field :year, class: "form-control"

    tr
      th = f.label :spec
      td
        - if @only_update
          = simple_format(f.object.spec)
        - else
          = f.text_area :spec, class: "form-control"

    tr
      th = f.label :condition
      td = f.text_area :condition, class: "form-control", placeholder: "例) 「試運転可」「ジャンク品(部品取り用)」「ドリル✕10本」など\n商品の状態、詳細などを記入して下さい"

    tr
      th = f.label :comment
      td.form-group
        = f.text_area :comment, class: "form-control"
        .help-block お客様には表示されません
    tr
      th = f.label :display
      td
        - if @only_update
          = f.object.display
        - else
          - Product.displays.each do |k, v|
            label.radio-inline = f.radio_button(:display, k, inline: true) + k
          p.help-block お客様には表示されません

    tr
      th = f.label :youtube
      td
        = f.text_field :youtube, class: "form-control youtube"
        = button_tag type: :button, id: "check-youtube", class: "btn btn-primary" do
            span.glyphicon.glyphicon-film
            span.btn-content Youtube確認

    tr
      th = f.label :featured do
        i.fa-solid.fa-award style="color:#ffd700;text-shadow:0 0 3px black;"
        span.btn-content 目玉商品
      td.form-group
        - if !@product.featured? && @product.featured_count >= Product::FEATURED_LIMIT
          .help-block
            | 目玉商品を設定できる件数は、#{Product::FEATURED_LIMIT}件までです。
        - else
          = f.check_box :featured, as: :boolean
          .help-block
            | チェックするとトップページ「目玉商品」に表示されます。(#{Product::FEATURED_LIMIT}件まで)

  = f.button :button, data: { "disable-with" => "保存中..." }, class: "btn btn-default btn-square btn-submit center-block" do
    span.glyphicon.glyphicon-save
    span.btn-content 保存

app/views/bid/products/_list.html.slim
= search_form_for search, url: "" do |s|
  = s.hidden_field :s, value: params.dig(:q, :s)
  ul.nav.nav-pills
    li = link_to({action: :new}, {class: "btn btn-default btn-square"}) do
      span.glyphicon.glyphicon-plus
      span.btn-content 新規登録

    li = s.button :submit, name: :format, value: :csv, class: "btn btn-default btn-square" do
      span.glyphicon.glyphicon-download-alt
      span.btn-content CSV出力

  - if products.blank?
    div 出品商品がありませんでした
  - else
    div 項目名をクリックすると、ソートすることができます

    .scroll_div
      table.table.table-striped.table-hover.table-condensed.table-bordered.table-responsive.table-products _fixedhead='rows:1'
        tr
          th.id = s.sort_link :app_no,      "申込No."
          th.id = s.sort_link :list_no,     "No."
          th = s.sort_link :genre_order_no, "ジャンル"
          th = s.sort_link :genre_order_no, "商品名"
          th = s.sort_link :maker,          "メーカー"
          th = s.sort_link :model,          "型式"
          th = s.sort_link :year,           "年式"
          th.num = s.sort_link :min_price,  "最低入札金額"
          th = s.sort_link :comment,        "備考欄"
          th.img_link 画像
          th.img_link 動画
          th.img_link = s.sort_link :featured, "目玉"
          th.button
        - products.each do |p|
          tr
            td.id = p.app_no
            td.id = p.list_no
            td = p.genre.name
            td = link_to p.name, { action: :edit, id: p.id }
            td = p.maker
            td = p.model
            td = p.year
            td.num = number_to_currency(p.min_price)
            td = p.comment
            td.img_link
              - if p.product_images.present?
                = link_to "/images/#{p.id}/", target: "_blank" do
                  span.glyphicon.glyphicon-picture
            td.img_link
              - if p.youtube.present?
                = link_to "/youtube/#{p.id}/", target: "_blank" do
                  span.glyphicon.glyphicon-film
            td.img_link
              - if p.featured?
                i.fa-solid.fa-award style="color:#ffd700;text-shadow:0 0 3px black;"
            td.button
              - if request.path =~ /system/ || @open_now.entry?
                - message = "#{p.name}\n\nこの出品商品を削除しますか？"
                = link_to({ action: :destroy, id: p.id }, method: :delete, data: { confirm: message, "disable-with" => "削除中..."}, class: "btn btn-default btn-xs") do
                  span.glyphicon.glyphicon-remove
                  span.btn-content 削除
        tr
          td colspan="6"
          td 合計金額
          td.num = number_to_currency(products.sum(:min_price))
          td colspan="4"

app/views/bid/products/csv.html.slim
- set_meta_tags title: "出品商品 CSV一括登録"
- breadcrumb  :bid_products_csv

ul.nav.nav-pills
  li = link_to "/products_template.csv", class: "btn btn-default btn-square" do
    span.glyphicon.glyphicon-download-alt
    span.btn-content テンプレートCSV
  li = link_to({action: :index, format: :csv, output: :import}, class: "btn btn-default btn-square") do
    span.glyphicon.glyphicon-download-alt
    span.btn-content 更新用CSV
    
= form_tag({action: :csv_upload}, multipart: true, method: :post, class: 'form-horizontal') do
  = render "csv"

app/views/bid/products/csv_upload.html.slim
- set_meta_tags title: "出品商品 CSV一括登録確認"
- breadcrumb  :bid_products_csv_upload

= render "csv_upload"

    
    
    
    

app/views/bid/products/edit.html.slim
- set_meta_tags title: "出品商品 変更"
- breadcrumb  :bid_products_edit, @product

= form_for @product, url: bid_product_path, method: :patch do |f|
  = render "form", f: f