config/routes.rb
Rails.application.routes.draw do
  devise_for :systems,
    path:        'system',
    path_names:  {sign_in: 'login', sign_out: 'logout'},
    only:        [:sessions],
    controllers: { sessions: 'system/sessions' }

  devise_for :companies,
    path:        'bid',
    path_names:  {sign_in: 'login', sign_out: 'logout'},
    only:        [:sessions],
    controllers: { sessions: 'bid/sessions' }

  devise_for :users,
    path: :users,
    path_names: {sign_in: 'login', sign_out: 'logout'},
    controllers: { registrations: 'users/registrations', confirmations: 'users/confirmations', sessions: 'users/sessions' }
  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end

  root to: "main#index"
  get "mltest" => "main#get_ml_genre"
  get "qrcode" => "main#qrcode"
  get "search" => "main#search"


  # get  "search"                      => "products#index", as: :search
  get  "xl_genre/:xl_genre_id"       => "products#index", as: :xl_genre
  get  "large_genre/:large_genre_id" => "products#index", as: :large_genre
  get  "genre/:genre_id"             => "products#index", as: :genre
  get  "special/:special_key"        => "products#index", as: :special

  # get  "detail/:id"   => "products#show"
  get "detail/:id" => redirect("/products/%{id}")

  resources :products, only: [:index, :show] do
    collection do
      get  :list_no
      get  :image_vector_search_by_file
      post :image_vector_search_by_file
      get  :image
      get  :search_by_list_no
    end

    member do
      get :image_vector_search
      get :images
      get :youtube
    end
  end

  # get  "images/:id"   => "products#images"
  # get  "youtube/:id"  => "products#youtube"
  # get  "bid_list"     => "products#bid_list"
  # get  "search_by_list_no" => "products#search_by_list_no"

  get "images/:id"  => redirect("/products/%{id}/images")
  get "youtube/:id" => redirect("/products/%{id}/youtube")
  get "bid_list"    => redirect("/products/list_no")
  get "search_by_list_no" => "products#search_by_list_no"

  get  "ml_get_genre" => "products#ml_get_genre"

  get  "qr"         => "products#qr"
  # get  "contact/:id"     => "products#contact"
  # post "contact/:id"     => "products#contact_do"
  # get  "contact_tel/:id" => "products#contact_tel"

  # get  "search_by_ml"      => "products#search_by_ml"

  # resources :wishlist, only: [:index, :create, :destroy]

  resources :contacts, only: [:new, :create] do
    collection do
      get :fin
    end
  end

  resources :detail_logs,  only: [:create]
  resources :toppage_logs, only: [:create]
  resources :search_logs,  only: [:create]

  # resources :helps, only: [:show]
  resources :helps, only: [] do
    collection do
      get :beginner
      get :faq
    end
  end

  get "search" => "main#search"


  ### マイページ ###
  namespace :mypage do
    root to: "main#index"

    get   'edit_password' => 'main#edit_password'
    patch 'edit_password' => 'main#update_password'
    get   'edit_user'     => 'main#edit_user'
    patch 'edit_user'     => 'main#update_user'

    resources :products,  only: [:index]
    resources :favorites, only: [:index, :create, :destroy] do
      collection do
        post  "toggle"
        patch "request_list"
      end
    end
    resources :contacts,  only: [:new, :create]
  end

  namespace :system do
    root to: "main#index"

    get   'edit_password' => 'main#edit_password'
    patch 'edit_password' => 'main#update_password'

    resources :opens do
      member do
        get "detail/:product_id" => :result_detail
      end

      member do
        get   :products
        get   :detail_logs
      end
    end
    resources :companies, except: [:show, :delete]
    resources :areas,     except: [:show]
    resources :infos,     only: [:index, :edit, :update]
    resources :displays,  only: [:index, :edit, :update]

    resources :products, except: [:show] do
      collection do
        get   :images
        get   :csv
        post  "csv" => :csv_upload
        patch "csv" => :csv_import
      end

      member do
        post   :image_upload
        delete ":product_image_id" => :image_destroy
        patch  :images_order
      end
    end

    resources :bids, except: [:show] do
      collection do
        # get :results
        get :rakusatsu_sum
        get :shuppin_sum
        get :total
        get :total_list
      end
    end

    resources :list, only: [:index, :new, :edit, :update] do
      collection do
        get :hangtag
        get :ef
        get :carry_out
        get :qr

        get    "carryout"     => :carryout_new
        get    "carryout/:id" => :carryout_edit
        patch  "carryout/:id" => :carryout_update
        delete "carryout/:id" => :carryout_destroy

        get :ads
      end
    end

    resources :bt, only: [:index, :new, :edit, :update] do
      collection do
        get    "carryout"     => :carryout_new
        get    "carryout/:id" => :carryout_edit
        patch  "carryout/:id" => :carryout_update
        delete "carryout/:id" => :carryout_destroy
      end
    end

    resources :users,        only: [:index, :show, :destroy]
    resources :contacts,     only: [:index]
    resources :favorites,    only: [:index]
    resources :detail_logs,  only: [:index]
    resources :toppage_logs, only: [:index]
    resources :search_logs,  only: [:index]

    resources :scheduling, only: [:index] do
      collection do
        post 'vectors_process'
        get  'recommend_products_mail'
        get  'tracking/:r/:dummy' => :tracking
      end
    end

    resources :total,  only: [:index] do
      collection do
        # get 'goal'
        get 'index2'
        get 'opens'
        get 'formula'
      end
    end

    unless Rails.env.production?
      resources :playground, only: [:show] do
        collection do
          get 'search_01'
          get 'search_02'
          post 'search_02'
          get 'image'

          get 'kmeans_01'


          get 'vector_maker'
          get 'vector_maker_solo'

          get "mock_list_01"
          get "mock_list_02"

          get 'vector_search_json'
        end
      end
    end

    resources :mailchimp_html, only: [:index]
    resources :mailchimp_user_html, only: [:index]
  end

  namespace :bid do
    root to: "main#index"

    get    'edit_password' => 'main#edit_password'
    patch  'edit_password' => 'main#update_password'

    get   'rule' => 'main#rule'
    patch 'rule' => 'main#rule_update'

    resources :products, except: [:show] do
      collection do
        get   :images
        get   :csv
        post  "csv" => :csv_upload
        patch "csv" => :csv_import
        get   :sim
      end

      member do
        post   :image_upload
        delete ":product_image_id" => :image_destroy
        patch  :images_order
      end
    end

    resources :bids, except: [:show] do
      collection do
        # get :results
        get :rakusatsu_sum
        get :shuppin_sum
        get :total
        get :motobiki
      end
    end

    resources :opens, only: [:index, :show]

    # resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
    #   collection do
    #     get   :csv
    #     post  "csv" => :csv_upload
    #     patch "csv" => :csv_import
    #   end
    # end
    #
    # resources :requests, only: [:index, :show, :update]
  end

  get '*path' => 'application#routing_error'
end

app/controllers/bid/opens_controller.rb
class Bid::OpensController < Bid::ApplicationController
  before_action :get_open, only: [:show]

  include Exports

  def index
    @opens = Open.order(bid_end_at: :desc)
  end

  def show
    redirect_to "/bid/opens/", alert: "#{@open.name}はまだ終了していません" if @open.bid_end_at > Time.now

    @open.result_sum unless @open.result

    @search    = @open.products.listed.with_keywords(params[:keywords])
      .includes(:success_bid, :success_company, :company, :genre, :product_images, :large_genre, :xl_genre, :area).search(params[:q])
    @products  = @search.result.order(:list_no).distinct
    @pproducts = @products.page(params[:page])

    @max_list_no = @open.products.listed.maximum(:list_no)

    @my_bids = current_company.bids.order(amount: :desc)

    respond_to do |format|
      format.html
      format.csv { export_csv "results.csv" }
    end
  end

  private

  def get_open
    @open = Open.find(params[:id])
  end
end

app/controllers/concerns/open_action.rb
class SystemAction
  # before_action時に呼び出される
  def before(controller)

    controller.logger.debug "before: #{controller.action_name}"


  end


end

app/controllers/system/application_controller.rb
class System::ApplicationController < ApplicationController
  before_action :authenticate_system!

  layout 'layouts/application'

  private

  def get_companies_selector
    @companies_selector = Company.order(:no).pluck("no || ' : ' || name", :id)
    session[:system_company_id] = params[:company_id] if params[:company_id].present?

    @company = Company.find_by(id: session[:system_company_id]) if session[:system_company_id].present?
  end

  def check_open
    redirect_to "/system/", notice: "現在、開催されている入札会はありません" unless @open_now
  end

  def check_entry_start
    redirect_to "/system/", notice: "現在、出品期間ではありません" unless @open_now.entry_start?
  end

  def check_bid_start
    redirect_to "/system/", notice: "現在、入札期間ではありません" unless @open_now.bid_start?
  end

  def check_result_list
    redirect_to "/system/", notice: "落札結果表示まで、しばらくお待ち下さい" unless @open_now.result_list?
  end

  def check_result_sum
    redirect_to "/system/", notice: "計算表表示まで、しばらくお待ち下さい" unless @open_now.result_sum?
  end
end

app/controllers/system/areas_controller.rb
class System::AreasController < System::ApplicationController
  before_action :get_area, only: [:edit, :update, :destroy]

  def index
    @areas = Area.all.order(:order_no)
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    if @area.save
      redirect_to "/system/areas/", notice: "#{@area.name}を登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @area.update(area_params)
      redirect_to "/system/areas/", notice: "#{@area.name}を変更しました"
    else
      render :edit
    end
  end

  def destroy
    @area.soft_destroy!
    redirect_to "/system/areas/", notice: "#{@area.name}を削除しました"
  end

  private

  def get_area
    @area = Area.find(params[:id])
  end

  def area_params
    params.require(:area).permit(:name, :image, :order_no, :remove_image)
  end
end

app/controllers/system/bids_controller.rb
class System::BidsController < System::ApplicationController
  before_action :check_open
  before_action :check_bid_start,   only: [:index, :new, :create, :destroy, :edit, :update, :destroy]
  before_action :check_result_list, only: [:results]
  before_action :check_result_sum,  only: [:rakusatsu_sum, :shuppin_sum, :total, :total_list]
  before_action :calc_result,       only: [:rakusatsu_sum, :shuppin_sum, :total, :total_list]

  before_action :get_companies_selector, except: [:results]
  before_action :bids, except: [:results]

  before_action :bid_init, only: [:new, :create]
  before_action :get_bid, only: [:edit, :update, :destroy]

  include Exports

  def index
    respond_to do |format|
      format.html
      format.pdf { export_pdf "#{@open_now.name}_bids.pdf", "/bid/bids/index.pdf" }
      format.csv { export_csv "#{@open_now.name}_bids.csv", "/bid/bids/index.csv" }
    end
  end

  def new
  end

  def create
    @bid.assign_attributes(bid_params)
    if params[:overcheck].to_i != @bid.amount && @over = @bid.check_5time
      render :new
    elsif @bid.present? && @bid.save
      redirect_to "/system/bids/new", notice: "#{@bid.product.name}に入札しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @bid.assign_attributes(bid_params)
    if params[:overcheck].to_i != @bid.amount && @over = @bid.check_5time
      render :edit
    elsif @bid.save
      redirect_to "/system/bids/", notice: "#{@bid.product.list_no} : #{@bid.product.name}の入札を訂正しました"
    else
      render :edit
    end
  end

  def rakusatsu_sum
    if @company
      @search   = @open_now.bids.where(company: @company).includes(:product, :genre, :success_bid).search(params[:q])
      @bids     = @search.result.order(:created_at)

      respond_to do |format|
        format.html
        format.pdf { export_pdf "rakusatsu.pdf", "/bid/bids/rakusatsu_sum.pdf" }
        format.csv { export_csv "rakusatsu.csv", "/bid/bids/rakusatsu_sum.csv" }
      end
    end
  end

  def shuppin_sum
    if @company
      @search   = @open_now.products.listed.where(company: @company).includes(:genre, :success_bid, :success_company).search(params[:q])
      @products = @search.result.order(:list_no)

      respond_to do |format|
        format.html
        format.csv { export_csv "shuppin.csv", "/bid/bids/shuppin_sum.csv" }
      end

    end
  end

  def total
    if @company
      @products         = @open_now.products.listed.where(company: @company).includes(:success_bid)
      @success_products = @open_now.bids.where(company: @company).includes(:product, :success_bid).success_products
    end
  end

  def destroy
    @bid.soft_destroy!
    redirect_to "/system/bids/", notice: "#{@bid.product.name}の入札を取り消しました"
  end

  def total_list
    all_products = @open_now.products.listed.includes(:success_bid, :success_company, :company)
    all_bids     = @open_now.bids.includes(:product, :success_bid, :product_company, :company)
    @companies = Company.order(:no)

    @company_products = @companies.map do |c|
      [
        c.id,
        {
          products:         all_products.where(company: c).order(:list_no),
          success_products: all_bids.where(company: c).success_products
        }
      ]
    end.to_h

    respond_to do |format|
      format.html
      # format.pdf { export_pdf "#{@open_now.name}_精算表.pdf" }
      format.pdf
      format.csv { export_csv "total.csv" }
    end
  end

  private

  def select_company_bids
    @companies = Company.order(:no).pluck("no || ' : ' || name", :id)

    session[:system_company_id] = params[:company_id] if params[:company_id].present?

    if session[:system_company_id].present? && @company = Company.find_by(id: session[:system_company_id])
      @search = @open_now.bids.where(company_id: session[:system_company_id]).search(params[:q])
      @bids   = @search.result
    else
      session[:system_company_id] = nil
      flash[:notice] = "会社を選択してください"
    end
  end

  def bids
    @search = @open_now.bids.where(company: @company).includes(:product, :genre).search(params[:q])
    @bids   = @search.result.order(created_at: :desc)
  end

  def bid_init
    @product = params[:list_no].present? ? @open_now.products.find_by(list_no: params[:list_no]) : nil
    @bid     = @product.bids.new(company: @company) if @product
  end

  def get_bid
    @bid = @bids.find(params[:id])
  end

  def calc_result
    @open_now.result_sum unless @open_now.result
  end

  def bid_params
    params.require(:bid).permit(:product_id, :amount, :comment)
  end
end

app/controllers/system/companies_controller.rb
class System::CompaniesController < System::ApplicationController
  include Exports

  def index
    @companies = Company.order(:no)

    respond_to do |format|
      format.html
      format.csv { export_csv "companies.csv" }
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to "/system/companies/", notice: "#{@company.name}を登録しました"
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    par = company_params
    par.delete(:password) if par[:password].blank?
    if @company.update(par)
      redirect_to "/system/companies/", notice: "#{@company.name}を変更しました"
    else
      render :edit
    end
  end

  # def destroy
  #   @company = Company.find(params[:id])
  #   @company.soft_destroy!
  #   redirect_to "/system/companies/", notice: "#{@company.name}を削除しました"
  # end

  private

  def company_params
    params.require(:company).permit(:name, :no, :registration_number, :charge,
      :representative, :position, :zip, :address, :tel, :fax, :mail, :memo, :entry, :transfer, :account, :password)
  end
end

app/controllers/system/contacts_controller.rb
class System::ContactsController < System::ApplicationController
  def index
    @contacts  = Contact.all.order(id: :desc)

    @pcontacts = @contacts.page(params[:page])
  end
end

app/controllers/system/displays_controller.rb
class System::DisplaysController < System::ApplicationController
  def index
    @displays = Display.order(:id)
  end

  def edit
    @display = Display.find(params[:id])
  end

  def update
    @display = Display.find(params[:id])
    @display.update(display_params)
  end

  private

  def display_params
    params.require(:display).permit(:display)
  end
end

app/controllers/system/favorites_controller.rb
class System::FavoritesController < System::ApplicationController
  include Exports
  include DateSelector

  before_action :date_selector, only: [:index]

  def index
    @favorites  = Favorite.unscoped.includes(:user,  product: [:company, :area, :success_bid, :success_company, genre: [large_genre: [:xl_genre]]]).where(@where).order(id: :desc)

    @pfavorites = @favorites.page(params[:page]).per(100)

    respond_to do |format|
      format.html
      format.csv { export_csv "favorite_logs.csv" }
    end
  end
end

app/views/system/opens/_form.html.slim
- if f.object.errors.full_messages.present?
  .alert.alert-danger
    ul
      - f.object.errors.full_messages.each do |msg|
        li = msg

table.table.table-hover.table-condensed.form-table
  tr
    th ID
    td.id = f.object.id || "新規登録"
  tr
    th = f.label :name, class: :required
    td = f.text_field :name, class: "form-control"

  tr
    th = f.label :owner, class: :required
    td = f.text_field :owner, class: "form-control"

  tr
    th = f.label :place, class: :required
    td = f.text_field :place, class: "form-control"
  tr
    th = f.label :addr, class: :required
    td = f.text_field :addr, class: "form-control"
  tr
    th = f.label :tel, class: :required
    td = f.text_field :tel, class: "form-control"
  tr
    th = f.label :fax, class: :required
    td = f.text_field :fax, class: "form-control"

  tr
    th: label.required 登録期間
    td.form-inline
      = f.text_field :entry_start_date, class: "form-control datepicker"
      = " 〜 "
      = f.text_field :entry_end_date, class: "form-control datepicker"
  tr
    th: label.required 搬入期間
    td.form-inline
      = f.text_field :carry_in_start_date, class: "form-control datepicker"
      = " 〜 "
      = f.text_field :carry_in_end_date, class: "form-control datepicker"
  tr
    th: label.required 下見期間
    td.form-inline
      = f.text_field :preview_start_date, class: "form-control datepicker"
      = " 〜 "
      = f.text_field :preview_end_date, class: "form-control datepicker"
  tr
    th: label.required 入札期間
    td.form-inline
      = f.text_field :bid_start_at, class: "form-control datetimepicker"
      = " 〜 "
      = f.text_field :bid_end_at, class: "form-control datetimepicker"
  tr
    th = f.label :user_bid_end_at, class: :required
    td.form-inline = f.text_field :user_bid_end_at, class: "form-control datetimepicker"

  tr
    th: label.required 搬出期間
    td.form-inline
      = f.text_field :carry_out_start_date, class: "form-control datepicker"
      = " 〜 "
      = f.text_field :carry_out_end_date, class: "form-control datepicker"

  tr
    th = f.label :billing_date, class: :required
    td.form-inline = f.text_field :billing_date, class: "form-control datepicker"
  tr
    th = f.label :payment_date, class: :required
    td.form-inline = f.text_field :payment_date, class: "form-control datepicker"

  tr
    th = f.label :lower_price, class: :required
    td.form-inline
      = f.number_field :lower_price, class: "form-control"
      = " 円"

  tr
    th = f.label :product_rate, class: :required
    td.form-inline
      = f.number_field :product_rate, class: "form-control"
      = " 円"
  tr
    th = f.label :rate, class: :required
    td.form-inline
      = f.number_field :rate, class: "form-control"
      = " 円"
  tr.form-inline
    th = f.label :tax, class: :required
    td
      = f.number_field :tax, class: "form-control"
      = " %"
= f.button data: { confirm: "保存してよろしいでしょうか", "disable-with" => "保存中..."}, class: "btn btn-default btn-square btn-submit center-block" do
  span.glyphicon.glyphicon-save
  span.btn-content 保存

app/views/system/opens/edit.html.slim
- set_meta_tags title: "入札会変更"
- breadcrumb  :system_opens_edit, @open

.col-md-offset-2.col-md-8
  = form_for @open, url: system_open_path, method: :patch do |f|
    = render "form", f: f

app/views/system/opens/index.html.slim
- set_meta_tags title: "入札会管理"
- breadcrumb  :system_opens

.container-fluid.list-menu
  = link_to({action: "new"}, class: "btn btn-default btn-square") do
    span.glyphicon.glyphicon-plus
    span.btn-content 新規登録

  / = link_to({format: :csv}, class: "btn btn-warning") do
  /   span.glyphicon.glyphicon-save-file
  /   =< "エクスポート"

- if @opens.blank?
  div 入札会がありませんでした
- else
  .scroll_div
    table.table.table-striped.table-hover.table-condensed.table-bordered.table-responsive.table-opens _fixedhead='rows:1'
      tr
        th ID
        th 入札会名
        th 出品期間
        th 下見期間
        th 入札期間
        th.button
        th colspan="2" Power BI用CSV
      - @opens.each do |o|
        tr
          td = o.id
          td = link_to o.name, "/system/opens/#{o.id}/edit"
          td #{o.entry_start_date.strftime('%Y/%-m/%-d %H:%M')} 〜 #{o.entry_end_date.strftime('%-m/%-d')}
          td #{o.preview_start_date.strftime('%Y/%-m/%-d %H:%M')} 〜 #{o.preview_end_date.strftime('%-m/%-d')}
          td #{o.bid_start_at.strftime('%Y/%-m/%-d %H:%M')} 〜 #{o.bid_end_at.strftime('%-m/%-d %H:%M')}
          td.button
            - if o.bid_end_at <= Time.now
              = link_to "落札結果", "/system/opens/#{o.id}"
            - else
              - message = "#{o.name}\n\nこの入札会を削除しますか？"
              = link_to "/system/opens/#{o.id}/", method: :delete, data: { confirm: message, "disable-with" => "削除中..."}, class: "btn btn-danger" do
                span.glyphicon.glyphicon-remove
                span.btn-conten 削除
          td.button
            - if o.bid_end_at <= Time.now
              = link_to "/system/opens/#{o.id}/products.csv" do
                i.fas.fa-file-csv
                span.btn-content 商品
          td.button
            - if o.bid_end_at <= Time.now
              = link_to "/system/opens/#{o.id}/detail_logs.csv" do
                i.fas.fa-file-csv
                span.btn-content 閲覧

app/views/system/opens/new.html.slim
- set_meta_tags title: "入札会新規登録"
- breadcrumb  :system_opens_new

.col-md-offset-2.col-md-8
  = form_for @open, url: "/system/opens", method: :post do |f|
    = render "form", f: f

app/views/system/opens/result_detail.html.slim
- set_meta_tags title: "#{@product.name} 入札詳細"
- breadcrumb  :system_opens_result_detail, @product

.row
  .col-sm-12.col-md-6
    .panel.panel-default
      .panel-heading 商品詳細
      .panel-body
        table.table.table-condensed.table-detail
          tr
            th リストNo.
            td = @product.list_no
          tr
            th ジャンル
            td #{@product.xl_genre.name} > #{@product.large_genre.name} > #{@product.genre.name}
          tr
            th 商品名
            td #{@product.name}
          tr
            th メーカー
            td #{@product.maker}
          tr
            th 型式
            td #{@product.model}
          tr
            th 最低入札金額
            td = number_to_currency(@product.min_price)
          tr
            th 年式
            td = @product.year
          tr
            th 展示場所
            td
             - if @product.display == "店頭出品"
              . = @product.company.try(:name)
              . = @product.company.try(:address)
             - else
                = @product.area.try(:name)
          tr
            th 仕様
            td = simple_format(@product.spec)
          tr
            th 現状
            td = simple_format(@product.condition)

  .col-sm-12.col-md-6
    - if @product.bid?
      .panel.panel-default
        .panel-heading 入札詳細
        .panel-body
          table.table.table-striped.table-hover.table-condensed
            tr
              th 入札会社名
              th 入札金額
              th 同額No.
              th 落札
            - @product.bids.order(amount: :desc, sameno: :desc).each.with_index do |b, i|
              tr
                td = b.company.name
                td.num = number_to_currency(b.amount)
                td.num = b.sameno
                td = i == 0 ? "◯" : ""

    / - if @product.youtube.present?
    /   .youtube-area <iframe width="560" height="315" src="https://www.youtube.com/embed/#{@product.youtube}" frameborder="0" allowfullscreen></iframe>
    / .imgs-area
    /   - if @product.product_images.size > 0
    /     - @product.product_images.each do |i|
    /       = image_tag i.image.view.url, style: "width:100%;"
    /   - else
    /     = image_tag "noimg_view.png", style: "width:100%;"

app/views/system/opens/show.html.slim
- set_meta_tags title: "#{@open.name} 落札結果一覧"
- breadcrumb  :system_opens_show, @open

= search_form_for @search, url: "/system/opens/#{@open.id}", class: "form-inline" do |s|
  = s.hidden_field :s, value: params.dig(:q, :s)
  ul.nav.nav-pills
    li = s.button :submit, name: :format, value: :csv, class: "btn btn-default btn-square" do
      span.glyphicon.glyphicon-download-alt
      span.btn-content CSV出力

  .pager-area
    - 1.step @max_list_no, 100 do |no|
      - lt_no = [@max_list_no, no + 99].min
      .list_no-link
        - if params.dig(:q, :list_no_gteq) == no.to_s
          strong #{no} 〜 #{lt_no}
        - else
          = link_to "#{no} 〜 #{lt_no}", "/system/opens/#{@open.id}?q[list_no_gteq]=#{no}&q[list_no_lteq]=#{lt_no}"

  .search-area
    = label_tag :list_no, "ジャンル ", class: :h4
    .form-group
      = s.grouped_collection_select :large_genre_id_eq, XlGenre.all.includes(:large_genres), :large_genres, :name, :id, :name, {include_blank: "すべてのジャンル"}, class: "form-control"

      = label_tag :list_no, "最低入札金額 ", class: :h4
      .form-group.form-priceinterval
        = s.text_field :min_price_gteq, placeholder: "〜以上", class: "form-control form-inline price"
        = " 〜 "
        = s.text_field :min_price_lteq, placeholder: "〜以下", class: "form-control form-inline price"

        = button_tag type: :submit, class: "btn btn-info" do
          .glyphicon.glyphicon-search
          span.btn-content 検索

  - if @pproducts.blank?
    div 該当の出品商品はありませんでした
  - else
    = paginate @pproducts
    .scroll_div style="margin: 0 calc(50% - 49vw);width: 98vw;"
      table.table.table-striped.table-hover.table-condensed.table-bordered.table-responsive.table-results _fixedhead='rows:1;cols:1;box-shadow:2px 2px 2px 0 rgba(0,0,0,0.2)'
        tr
          th.id = s.sort_link :list_no,         "No."
          th = s.sort_link :genre_order_no,     "ジャンル"
          th = s.sort_link :name,               "商品名"
          th = s.sort_link :maker,              "メーカー"
          / th = s.sort_link :model,              "型式"
          th.img_link 画像
          th.img_link 動画
          th.num = s.sort_link :min_price,      "最低入札金額"
          th.sepa = s.sort_link :company_id,    "出品会社"

          th.no = s.sort_link :bids_count,      "入札数"
          th.num = s.sort_link :success_bid_amount, "落札金額"
          th = s.sort_link :success_company_no, "落札会社"
          th.no.sepa = s.sort_link :same_count, "同額札"
          th = s.sort_link :carryout_at,        "出庫日時"
        - @pproducts.each do |p|
          tr
            td.id = p.list_no
            td = p.genre.name
            td = link_to_if p.success_bid.present?, p.name, "/system/opens/#{@open.id}/detail/#{p.id}"
            td = p.maker
            / td = p.model
            td.img_link
              - if p.product_images.present?
                = link_to "/images/#{p.id}/", target: "_blank" do
                  span.glyphicon.glyphicon-picture
            td.img_link
              - if p.youtube.present?
                = link_to "/youtube/#{p.id}/", target: "_blank" do
                  span.glyphicon.glyphicon-film
            td.num = number_to_currency(p.min_price)
            td.sepa = p.company.name

            - if p.success_bid.present?
              td.no = p.bids_count
              td.num = number_to_currency(p.success_bid.amount)
              td = p.success_company.name
              td.sepa = p.same_count if p.same_count > 1

            - else
              td.no
              td.num
              td
              td.no.sepa
            td = p.carryout_at.present? ? l(p.carryout_at, format: :short) : ""